### ISSUE TITLE
Failed github actions as of recently

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/.github#202]
Hi,

_I'm aware this is definitely not the right place for this issue, but frankly, I don't know where is._

I'm the developer of [NextcloudPi](https://github.com/nextcloud/nextcloudpi) and I'm very thankful that we can use a repository under the nextcloud namespace.
During the last years, we have moved all of our build processes to Github actions and, because that's probably enforced by an admin policy for the github.com/nextcloud org, we can only use self hosted runners for this, which in this case means runners hosted by Nextcloud (with one exception for arm64 builds). I wasn't actually aware of this until I tracked down a bug with our pipelines lately.

**Anyways here's my current issue:** since at least July, we have issues with all of our armbian builds, because the worker jobs run out of disk space. I assume there has been a change in the runner configuration that causes this. Is there any way to either
1) Change the runner configuration to provide slightly more disk space or
2) allow Github-hosted runners for the nextcloudpi repository

Hosting our own runner cluster is not an option unfortunately, because the project is entirely non-profit and that would mean a significant cost factor for me :)

Here is an example for the kind of errors we receive:

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.306.0/_diag/Worker_20230726-203451-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.306.0/_diag/Worker_20230726-203451-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.306.0/_diag/Worker_20230726-203451-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

**Comment by skjnldsv** [comment]
Hey! :)

We offer the same specs as the official runners :thinking: 
If you want to make sure to not use our runners, you can adjust your workflows by using `ubuntu-22.04` instead of `ubuntu-latest`

cc @marcelklehr

**Comment by marcelklehr** [comment]
misnomer? Not sure how I can help here?

**Comment by theCalcaholic** [comment]
@skjnldsv Thank you, I'll verify if I encounter the same issues with the official runners then. If yes, I'll look into a feasible alternative :)

**Comment by skjnldsv** [comment]
Keep me updated :)
